
DOMAIN_SHORT_NAME = 'cognerium'
DOMAIN_FULL_NAME = 'Cognerium Research Labs India'
DOMAIN = DOMAIN_SHORT_NAME+'.com'
SECURE = True
DOMAIN_URL = ('https' if SECURE else 'http') + '://'+DOMAIN
COMPANY_FULL_NAME = 'Cognerium Research Labs India Pvt Ltd'
COMPANY_SHORT_NAME = 'cognerium'
LOGO = "https://i.imgur.com/RqNSLyZ.png"
DOMAIN_EMAIL = 'admin@'+DOMAIN
DOMAIN_SUPPORT_EMAIL = 'support@'+DOMAIN
DOMAIN_SUPPORT_URL = DOMAIN_URL+'/company/support/'
PRESS_EMAIL = 'press@'+DOMAIN
CAREERS_EMAIL = 'careers@'+DOMAIN
PAYMENTS_EMAIL = 'payments@'+DOMAIN
PRESS_EMAIL = 'press@'+DOMAIN
WELCOME_EMAIL = 'welcome@'+DOMAIN
ADMIN_EMAIL = 'admin@'+DOMAIN
MOBILE_SUPPORT='+91 88888 88888'

CEO = {
    "name": "",
    "email": "admin@"+DOMAIN,
    "mobile": "+91 888888888888"
}

ROOM_CODE_LENGTH = 10
CAMPAIGN_TASK_BATCH_CODE_LENGTH = 8
USERNAME_MIN_LENGTH = 5
USERNAME_MAX_LENGTH = 12
CODE_LENGTH = 8
PASSWORD_MIN_LENGTH=6
OTP_LENGTH = 6
OTP_EXPIRY = 15*60 #15 minutes
OTP_TRIES=3

